In [1]:
#Eincsum practice
import numpy as np

In [ ]:
#Unary Operation

In [2]:
#Transpose
A = np.array([[1,2,3],
              [4,5,6]])

R = np.einsum("ij->ji",A)
print(R)

[[1 4]
 [2 5]
 [3 6]]


In [3]:
#Diagonal,Trace

A = np.eye(10)
print(A)
print()

diag = np.einsum("ii->i",A)
trace = np.einsum("ii->",A)
print(diag)
print()
print(trace)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

10.0


In [5]:
#Summation
A = np.array([[1,2,3],
              [4,5,6]])

R = np.einsum("ij->",A)
print(R)

21


In [6]:
#Matric Colum or row sum(to vector)

A = np.array([[1,2,3],
              [4,5,6]])

row_sum = np.einsum("ij->i",A)
col_sum = np.einsum("ij->j",A)
print(row_sum)
print()
print(col_sum)

[ 6 15]

[5 7 9]


In [9]:
#Dot Product,Outer Product of two vectors 

x = np.array([-1,-10,-100])
y = np.array([1,10,100])

dot = np.einsum("i,i->",x,y)
outer = np.einsum("i,j->ij",x,y)

print(dot)
print()
print(outer)


-10101

[[    -1    -10   -100]
 [   -10   -100  -1000]
 [  -100  -1000 -10000]]


In [12]:
#Hadamard product of vector or matrix

x = np.array([-1,-10,-100])
y = np.array([1,10,100])
print(np.einsum("i,i->i",x,y))

A = np.arange(6).reshape(2,3)
B = np.arange(6).reshape(2,3)

elemwise_mate = np.einsum("ij,ij->",A,B)
print(elemwise_mate)

[    -1   -100 -10000]
55


In [13]:
#Matrix-Vector Multiplication 

A = np.array([[1,2,3],
              [4,5,6]])

x = np.array([-1,-2,-100])

b = np.einsum("ij,j->i",A,x)

print(b)

[-305 -614]


In [18]:
#Matrix-Matrix Multiplication and Batched Matrix Muliplication
A = np.array([[1,2,3],
              [4,5,6]])

B = A.transpose()

R = np.einsum("ik,kj->ij",A,B)
print(R.shape)
print()

A = np.random.random(size=(3,10,4))
B = np.random.random(size=(3,4,8))

R = np.einsum("bik,bkj->bij",A,B)
print(R.shape)
print()

(2, 2)

(3, 10, 8)



In [19]:
#Quadritc Form, Matric Norm, Distance with repect to Matric 

x = np.array([1,2,3])
y = np.array([-1,-2,-3])
A = np.random.random(size =(3,3))

r = np.einsum("i,ij,j->",x,A,y)
print(r)

-17.563032176080824
