In [1]:
import matplotlib.pyplot as plt 
import pandas as pd 
import numpy as np

import torch

In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
## Creating Tensors 

# Scalar
print("Scalar")
scalar = torch.tensor(7) # singlue number is printed
print(scalar)
print(scalar.ndim)
print(scalar.item()) # retrieve the number from tensor : torch.tensor -> python int
print()

# Vector 
print("Vector")
vector = torch.tensor([7,7])
print(vector)
print(vector.shape)
print()

# Matrix 
print("Matirx")
matrix = torch.tensor([[7,8],
                       [9,10]])

print(matrix.ndim)
print(matrix.shape)


Scalar
tensor(7)
0
7

Vector
tensor([7, 7])
torch.Size([2])

Matirx
2
torch.Size([2, 2])


In [4]:
## Creating Random Tensor 

In [5]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(size = (3,4))
print(random_tensor)
print()
print(random_tensor.dtype)
print()
print(random_tensor.shape)

tensor([[0.1327, 0.1524, 0.4575, 0.1411],
        [0.5593, 0.3021, 0.4546, 0.1603],
        [0.9137, 0.7477, 0.5978, 0.4048]])

torch.float32

torch.Size([3, 4])


In [6]:
## Creating Tensors with Zeros and Ones 

In [20]:
print("Zeros")
zeros = torch.zeros(size = (3,4))
print(zeros)
print()
print(zeros.dtype)
print()
print(zeros.shape)
print()

print("Ones")
ones = torch.ones(size = (3,4))
print(ones)
print()
print(ones.dtype)
print()
print(ones.shape)


Zeros
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.float32

torch.Size([3, 4])

Ones
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

torch.float32

torch.Size([3, 4])


In [8]:
## Creating a range and tensors like 

In [9]:
zero2ten = torch.range(0,10)
print(zero2ten)
print()
#application 

zero2ten_onelike = torch.ones_like(input = zero2ten)
print(zero2ten_onelike)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


<ipython-input-9-07a4532f3771>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero2ten = torch.range(0,10)


In [10]:
## Tensor Data types 

In [11]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)

float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = torch.float16)

print("32")
print(float_32_tensor)
print(float_32_tensor.dtype)
print(float_32_tensor.device)
print()
print("16")
print(float_16_tensor)
print(float_16_tensor.dtype)
print(float_16_tensor.device)

32
tensor([3., 6., 9.])
torch.float32
cpu

16
tensor([3., 6., 9.], dtype=torch.float16)
torch.float16
cpu


In [12]:
## Manipulating Tensor 
tensor = torch.tensor([1,2,3])
tensor + 10
print(tensor+10)
print(torch.add(tensor,10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [13]:
# Addition 
tensor * 10
print(tensor * 10)
print(torch.multiply(tensor,10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [14]:
# Subtraction 
tensor-10

tensor([-9, -8, -7])

In [15]:
# Multiplication(Elment-wise)
print(tensor * tensor)

tensor([1, 4, 9])


In [16]:
# Division
print(tensor/2)

tensor([0.5000, 1.0000, 1.5000])


In [17]:
# Matrix Multiplication 
# torch.matmul()
# @ 
# torch.mm() -> short cut for matmul 

print(torch.matmul(tensor,tensor)) 
print(tensor @ tensor)

tensor(14)
tensor(14)


In [18]:
## Transpose 

In [19]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [21]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [22]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [23]:
print(torch.mm(tensor_A,tensor_B.T))

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [ ]:
## Finding the min,max,mean,sum,etc(aggregation)

In [24]:
x = torch.arange(0,100,10)
print(x)
print(x.max())
print(x.min())
print(x.type(torch.float32).mean()) # You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.
print(x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(90)
tensor(0)
tensor(45.)
tensor(450)


In [ ]:
# positional min,max(argmin, argmax )

In [25]:
print(x.argmax())
print(x.argmin())
# Returns index of max and min values 

tensor(9)
tensor(0)


In [ ]:
## Reshaping, stacking, squeezing and unsqueezing 

In [27]:
# torch.reshape()
x = torch.arange(7)
print(x)
x.reshape(1,7)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5, 6])


In [29]:
# torch.view()
x = torch.arange(7)
print(x)
x.view(1,7)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5, 6])


In [33]:
# stack
x_stacked_dim_0 = torch.stack([x,x,x,x],dim = 0)
print(x_stacked_dim_0)
print()
x_stacked_dim_1 = torch.stack([x,x,x,x],dim = 1)
print(x_stacked_dim_1)

tensor([[0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6]])

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])


In [42]:
# squeeze 

x = torch.ones(2,2,1,3)
print(x)
print()
print(x.squeeze())
print()
print(x.squeeze().shape)
print()
print(x.squeeze(dim= 2))
print()
print(x.squeeze(dim= 2).shape)

tensor([[[[1., 1., 1.]],

         [[1., 1., 1.]]],


        [[[1., 1., 1.]],

         [[1., 1., 1.]]]])

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

torch.Size([2, 2, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

torch.Size([2, 2, 3])


In [48]:
x = torch.ones(2,2)
print(x)
print()
print(x.unsqueeze(dim=0))
print()
print(x.unsqueeze(dim=0).shape)
print()
print(x.unsqueeze(dim=1))
print()
print(x.unsqueeze(dim=1).shape)
print()
print(x.unsqueeze(dim=2))
print()
print(x.unsqueeze(dim=2).shape)

tensor([[1., 1.],
        [1., 1.]])

tensor([[[1., 1.],
         [1., 1.]]])

torch.Size([1, 2, 2])

tensor([[[1., 1.]],

        [[1., 1.]]])

torch.Size([2, 1, 2])

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

torch.Size([2, 2, 1])


In [ ]:
## PyTorch tensors & NumPy

In [34]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
nump  = tensor.numpy()
print(array)
print(tensor)
print(nump)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
[1. 2. 3. 4. 5. 6. 7.]


In [35]:
# random number

rand_a = torch.rand(3,4)
print(rand_a)
print()
rand_b = torch.rand(3,4)
print(rand_b)

tensor([[0.9188, 0.1892, 0.0691, 0.4367],
        [0.3213, 0.2408, 0.2734, 0.2664],
        [0.7847, 0.5156, 0.7004, 0.7801]])

tensor([[0.0367, 0.9105, 0.7501, 0.0284],
        [0.2558, 0.5558, 0.8939, 0.8905],
        [0.7208, 0.0066, 0.5334, 0.7474]])
